-- MailController.lua
-- Modular Auto Mail send/claim controller ported from gag2.lua mail flow.
local MailController = {}
local sending = false
local runningClaim = false
local GEAR_ATTR_CATEGORY={Sprinkler="Sprinklers",WateringCan="WateringCans",Mushroom="Mushrooms",Gnome="Gnomes",Raccoon="Raccoons",Crate="Crates",SeedPack="SeedPacks",Trowel="Trowels",Prop="Props",EmptyPot="EmptyPots"}
local function parseMoneyInput(text) text=tostring(text or ""):lower():gsub(",",""):gsub("%s+",""); if text=="" then return 0 end; local num,suf=text:match("^([%d%.]+)([kmbtq]?)$"); num=tonumber(num); if not num then return 0 end; local mult=suf=="k" and 1e3 or suf=="m" and 1e6 or suf=="b" and 1e9 or suf=="t" and 1e12 or suf=="q" and 1e15 or 1; return math.floor(num*mult) end
local function formatMoneyCompact(v) v=tonumber(v) or 0; local a=math.abs(v); if a>=1e12 then return string.format("%.2fT",v/1e12) elseif a>=1e9 then return string.format("%.2fB",v/1e9) elseif a>=1e6 then return string.format("%.2fM",v/1e6) elseif a>=1e3 then return string.format("%.2fK",v/1e3) end; return tostring(math.floor(v)) end
local function selectedKeys(value) if type(value)=="table" then local out={}; for _,v in ipairs(value) do if type(v)=="string" and v~="" and v~="Select Options" then table.insert(out,v) end end; return out end; if type(value)=="string" and value~="" and value~="Select Options" then return {value} end; return {} end
local function chunkPayload(payload, chunkSize, maxBatches) local chunks={}; chunkSize=math.max(1,tonumber(chunkSize) or 20); maxBatches=math.max(1,tonumber(maxBatches) or 1); for i=1,#payload,chunkSize do if #chunks>=maxBatches then break end; local c={}; for j=i,math.min(i+chunkSize-1,#payload) do table.insert(c,payload[j]) end; table.insert(chunks,c) end; return chunks end
function MailController.init(deps) deps=deps or {}; MailController.Logger=deps.Logger; MailController.Cfg=deps.Cfg or {}; MailController.Networking=deps.Networking; MailController.LocalPlayer=deps.LocalPlayer; MailController.calcFruitValue=deps.calcFruitValue; MailController.FeatureRegistry=deps.FeatureRegistry; if MailController.FeatureRegistry then MailController.FeatureRegistry.set("Mail","modular") end; return MailController end
function MailController.notify(msg) warn("[Auto Mail] "..tostring(msg)) end
function MailController.getGearCategory(tool) for attr,cat in pairs(GEAR_ATTR_CATEGORY) do local v=tool:GetAttribute(attr); if v~=nil then return cat,attr,v end end; return nil end
function MailController.collectFruits(key) local out={}; local any=(#selectedKeys(key)==0); local keySet={}; for _,k in ipairs(selectedKeys(key)) do if k=="All" or k=="*" then any=true else keySet[k]=true end end; local bp=MailController.LocalPlayer and MailController.LocalPlayer:FindFirstChild("Backpack"); if not bp then return out end; local minV,maxV=parseMoneyInput(MailController.Cfg.mailFruitMinValue),parseMoneyInput(MailController.Cfg.mailFruitMaxValue); if maxV<=0 then maxV=math.huge end; for _,v in ipairs(bp:GetChildren()) do if v:GetAttribute("HarvestedFruit")==true and v:GetAttribute("Id") and v:GetAttribute("IsFavorite")~=true then local name=v:GetAttribute("FruitName") or v:GetAttribute("Fruit") or v.Name; if any or keySet[name] then local val=0; if type(MailController.calcFruitValue)=="function" then val=MailController.calcFruitValue(name,v:GetAttribute("SizeMultiplier") or 1,v:GetAttribute("Mutation") or "",v:GetAttribute("DecayAlpha") or 0,true) end; if val>=minV and val<=maxV then table.insert(out,{inst=v,id=v:GetAttribute("Id"),name=name,weight=tonumber(v:GetAttribute("Weight")) or 0,value=val}) end end end end; return out end
function MailController.buildMailPayloadBatches() local cfg=MailController.Cfg or {}; local cat,key,count=cfg.mailCategory,cfg.mailItemKey,math.max(1,tonumber(cfg.mailCount) or 1); local userBatch=cfg.mailSendMode=="Batch Loop" and math.max(1,tonumber(cfg.mailBatchSize) or 20) or nil; local bp=MailController.LocalPlayer and MailController.LocalPlayer:FindFirstChild("Backpack"); if not bp then return nil,"Backpack not found" end; local payload={}; if cat=="Fruits" then local fruits=MailController.collectFruits(key); table.sort(fruits,function(a,b) if a.value==b.value then return a.weight<b.weight end; return a.value<b.value end); local total=0; for i=1,math.min(count,#fruits) do table.insert(payload,{Category="HarvestedFruits",ItemKey=fruits[i].id,Count=1}); total+=fruits[i].value or 0 end; if #payload==0 then return nil,"No matching non-favorite fruits" end; local sz=userBatch or 999999; return chunkPayload(payload,sz,math.max(1,math.ceil(#payload/sz))), string.format("%d fruit | %s",#payload,formatMoneyCompact(total)) end; local keys={}; for _,k in ipairs(selectedKeys(key)) do keys[k]=true end; for _,v in ipairs(bp:GetChildren()) do if cat=="Seeds" then local seed=v:GetAttribute("SeedTool"); if seed and keys[seed] then table.insert(payload,{Category="Seeds",ItemKey=seed,Count=math.min(count,v:GetAttribute("Count") or 1)}) end elseif cat=="Gear" then local gearCat,_,gearKey=MailController.getGearCategory(v); local itemKey=type(gearKey)=="string" and gearKey or v.Name; if gearCat and keys[itemKey] then table.insert(payload,{Category=gearCat,ItemKey=itemKey,Count=math.min(count,v:GetAttribute("Count") or 1)}) end elseif cat=="Pets" then local pet=v:GetAttribute("Pet"); if pet and keys[pet] and v:GetAttribute("PetId") then table.insert(payload,{Category="Pets",ItemKey=v:GetAttribute("PetId"),Count=1}) end end end; if #payload==0 then return nil,"Item not found" end; local sz=userBatch or 999999; return chunkPayload(payload,sz,math.max(1,math.ceil(#payload/sz))), cat.." "..tostring(#payload).." item(s)" end
function MailController.sendBatches(batches,summary) local mb=MailController.Networking and MailController.Networking.Mailbox; if not (mb and mb.SendBatch) then return false,"Mailbox send remote unavailable" end; for i,payload in ipairs(batches or {}) do if not (MailController.Cfg or {}).autoMailSend then return false,"Mail send cancelled" end; local ok,success,msg=pcall(function() return mb.SendBatch:Fire(MailController.Cfg.mailTargetId,payload,"") end); if not ok or success==false then return false,tostring(msg or "Invalid items") end; if i<#batches then task.wait(math.max(tonumber(MailController.Cfg.mailDelay) or 9,9)) end end; return true,summary end
function MailController.sendStart() if sending then return false,"Mail already running" end; sending=true; local ok,err=xpcall(function() local target=tonumber(MailController.Cfg.mailTargetId) or 0; if target<=0 then return false,"No valid target set" end; local batches,summary=MailController.buildMailPayloadBatches(); if not batches then return false,summary end; return MailController.sendBatches(batches,summary) end,debug.traceback); sending=false; if not ok then return false,err end; MailController.Cfg.autoMailSend=false; return true end
function MailController.claimOnce() local mb=MailController.Networking and MailController.Networking.Mailbox; if not (mb and mb.OpenInbox and mb.Claim) then return false,"Mailbox claim remotes unavailable" end; local total=0; local seen={}; for pass=1,5 do local ok,inbox=pcall(function() return mb.OpenInbox:Fire() end); if not ok or type(inbox)~="table" then return total>0,"OpenInbox failed" end; local passCount,claimed=0,0; for mailId in pairs(inbox) do if not MailController.Cfg.autoMailClaim then break end; if not seen[tostring(mailId)] then seen[tostring(mailId)]=true; passCount+=1; local okClaim,success=pcall(function() return mb.Claim:Fire(mailId) end); if okClaim and success~=false then total+=1; claimed+=1 end; task.wait(0.18); if passCount>=60 then break end end end; if passCount==0 or claimed==0 then break end; task.wait(0.75) end; return total>0,"claimed="..tostring(total) end
function MailController.claimStart() if runningClaim then return true end; runningClaim=true; task.spawn(function() while runningClaim do if (MailController.Cfg or {}).autoMailClaim then pcall(MailController.claimOnce) end; task.wait(10) end end); return true end
function MailController.stop() sending=false; runningClaim=false; return true end
return MailController
